[technote]
id = "SITCOMTN-120"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-120.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-120"
github_default_branch = "main"
date_created = 2024-03-17T20:37:03Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

#[[technote.authors]]
#name.given = "Bruno C."
#name.family = "Quint"
#internal_id = "quintb"
#orcid = "https://orcid.org/0000-0002-1557-3560"
#[[technote.authors.affiliations]]
#name = "Rubin Observatory Project Office"
#internal_id = "RubinObs"
#address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
[[technote.authors]]
name.given = "Joaquín"
name.family = "Hernández"